# apiVersion: v1 # Specifies the API version of the Kubernetes resource
# kind: PersistentVolumeClaim # Specifies that this resource is a PersistentVolumeClaim
# metadata:
#   name: ml-app-pvc # The name of the PersistentVolumeClaim resource
# spec:
#   accessModes:
#   - ReadWriteMany # Access mode indicating multiple nodes can read and write
#   resources:
#     requests:
#       storage: 1Gi # Amount of storage requested for the PVC
#   volumeName: ml-app-pv # The name of the PersistentVolume to bind to

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-app-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
