# apiVersion: v1 # API version of Kubernetes resource
# kind: PersistentVolume # Type of resource
# metadata:
#   name: ml-app-pv # Name of the PersistentVolume
# spec:
#   capacity:
#     storage: 1Gi # Size of the PersistentVolume
#   accessModes:
#   - ReadWriteMany # Access mode, allows multiple nodes to read/write
#   hostPath:
#     path: /home/lithira/docker_data # Path on the host where the data is stored (replace `your-username`)

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/lithira/docker_data
