apiVersion: v1 # Specifies the API version of the Kubernetes resource
kind: Service # Specifies that this resource is a Service
metadata:
  name: ml-app-service # The name of the Service resource
spec:
  selector:
    app: ml-app # Label selector to match the pods (must match the labels defined in the deployment)
  ports:
  - protocol: TCP # The protocol used by the service
    port: 80 # The port that the service will expose
    targetPort: 5000 # The port on the pod that the service should forward traffic to
  type: LoadBalancer # The type of the service (LoadBalancer to expose externally)


# apiVersion: v1
# kind: Service
# metadata:
#   name: ml-app-service
# spec:
#   selector:
#     app: ml-app
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000
#     name: http-ml-app-container-1
#   - protocol: TCP
#     port: 81 # Different external port for the second container
#     targetPort: 5001
#     name: http-ml-app-container-2
#   type: LoadBalancer

