apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-config
  namespace: kube-system
data:
  config.toml: |
    version = 1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: 5
