apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      containers:
      - name: nvidia-device-plugin-ctr
        image: nvcr.io/nvidia/k8s-device-plugin:v0.13.0
        args: ["--config-file", "/config/config.toml"]
        volumeMounts:
        - name: config
          mountPath: /config
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: config
        configMap:
          name: nvidia-device-plugin-config
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
